# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(default=0, max_length=250)),
                ('total_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.FloatField(default=0)),
                ('item_name', models.CharField(default=0, max_length=250)),
                ('quantity_no', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_details', to='bill.Order')),
            ],
        ),
    ]
