# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_order_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_details',
            new_name='Order_detail',
        ),
    ]
